- name: Reboot Device
  block:
  - name: Issue Reboot Command
    icx_command: {commands: 'boot system flash {{BootPart}} yes'}
    register: rReboot
    failed_when: false

  - name: Pause If Error Returned
    wait_for: {host: , port: }
    when: "'Error' in rReboot.stdout[0]|default()"

  - name: Flag Successful Reboot
    set_fact: {RebootSuccess: true}
    when: (rReboot.stdout[0] is defined and "Error" not in rReboot.stdout[0])
          or "command timeout triggered" in rReboot.msg|default()
  when: RebootSuccess is not defined or not RebootSuccess
