vNeedAwxSshCreds: '{{awxssh_user|default("null", true) == "null"}}'
vIcxImgDirCreated: '{{icx_awx_mgmt.img_mgmt.awx_image_dir is defined}}'
vAwxImgDir: '{{icx_awx_mgmt.img_mgmt.awx_image_dir|default()}}'


awxcli_prompts:
  - question_name: "AWX Server CLI Credential - SSH Login Username:"
    required: true
    type: text
    variable: prompt_awxcli_user
    min: 1
    max: 32
  - question_name: "AWX Server CLI Credential - SSH Login Password:"
    required: true
    type: password
    variable: prompt_awxcli_pass
    min: 1
    max: 1024
  - question_name: "AWX Server CLI Credential - Sudo Password:"
    question_description: Leave blank to use SSH login password.
    required: false
    type: password
    variable: prompt_awxcli_sudo
    min: 1
    max: 1024


awx_tmplt_mgmt_prompts:
  - question_name: "Update Image Management Templates?"
    question_description: "Image Repo Location: {{vAwxImgDir}}"
    required: true
    type: multiplechoice
    variable: prompt_update_img_mgmt
    default: "Yes"
    choices: |-
      Yes
      No


awx_tmplt_mgmt_survey:
  - question_name: "Template management function:"
    required: false
    type: multiplechoice
    variable: prompt_mgmt_role
    choices: |-
      Create/Update Templates
      Remove ICX Config Templates
  - '{{awx_tmplt_mgmt_prompts[0] if vIcxImgDirCreated else []}}'
  - '{{awxcli_prompts[0] if vIcxImgDirCreated and vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[1] if vIcxImgDirCreated and vNeedAwxSshCreds else []}}'


# image_management
img_mgmt_survey:
  - question_name: "Image Repository Path:"
    required: true
    type: text
    variable: prompt_imgrepo_path
    default: '{{vAwxImgDir|default("/opt/Images", true)}}'
  - '{{awxcli_prompts[0] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[1] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[2] if vNeedAwxSshCreds else []}}'


image_flash_copy_file_survey:
  - question_name: "FastIron Image File:"
    required: true
    type: multiplechoice
    variable: prompt_flash_copy_filename
    choices: '{{SwImgFileList|default()}}'
  - question_name: "Boot Image File:"
    required: true
    type: multiplechoice
    variable: prompt_bootflash_copy_filename
    choices: '{{BootFileNames|default("None\nAuto Select")}}'
    default: Auto Select
  - question_name: "Flash Partition:"
    required: true
    type: multiplechoice
    variable: prompt_flash_part
    choices: |-
      Primary
      Secondary
    default: Secondary
  - question_name: "Configure Selected Flash Partition as First in Boot Order?"
    required: true
    type: multiplechoice
    variable: prompt_flash_change_boot
    choices: |-
      Yes
      No
    default: "Yes"
  - question_name: "Reboot Into New Image After Deployment?"
    required: true
    type: multiplechoice
    variable: prompt_flash_reload
    choices: |-
      Yes
      No
    default: "No"
  - '{{awxcli_prompts[0] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[1] if vNeedAwxSshCreds else []}}'
  - question_name: "Image Repo Server Hostname:"
    required: true
    type: multiplechoice
    variable: prompt_image_repo_hostname
    default: '{{inventory_hostname}}'
    choices: '{{inventory_hostname}}'
  - question_name: "SCP Server Address:"
    required: true
    type: multiplechoice
    variable: prompt_image_repo_address
    default: '{{ansible_host}}'
    choices: '{{ansible_host}}'


image_flash_copy_version_survey:
  - question_name: "FastIron Version:"
    required: true
    type: multiplechoice
    variable: prompt_flash_copy_version
    choices: "{{SwImgVerList|default()|unique|sort|join('\n')}}"
  - question_name: "FastIron Image Type:"
    required: true
    type: multiplechoice
    variable: prompt_image_type
    choices: |-
      Switch
      Router
    default: Router
  - question_name: "Boot Image Selection Method:"
    required: true
    type: multiplechoice
    variable: prompt_bootflash_copy_filename
    choices: |-
      None
      Auto Select
    default: Auto Select
  - '{{image_flash_copy_file_survey[2]}}'
  - '{{image_flash_copy_file_survey[3]}}'
  - '{{image_flash_copy_file_survey[4]}}'
  - '{{awxcli_prompts[0] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[1] if vNeedAwxSshCreds else []}}'
  - '{{image_flash_copy_file_survey[7]}}'
  - '{{image_flash_copy_file_survey[8]}}'


image_flash_copy_templates:
- name: Image-Flash-Copy-File
  playbook_rev: 1.0.0
  description: "Copy files(s) to switch"
  playbook: Image-Flash-Copy.yml
  survey_spec: '{{image_flash_copy_file_survey|select()|list}}'

- name: Image-Flash-Copy-Version
  playbook_rev: 1.0.0
  description: "Update switch(es) to selected version"
  playbook: Image-Flash-Copy.yml
  survey_spec: '{{image_flash_copy_version_survey|select()|list}}'


# ztp_managment
ztp_management_survey:
  - question_name: "Provisioning Inventory:"
    question_description: Name of inventory used for ZTP hosts
    required: true
    type: text
    variable: prompt_ztp_inventory
    min: 1
    max: 1024
    default: Provisioning
  - question_name: "Configure Secondary Interface:"
    question_description: "(optional) Configure IP address on secondary interface"
    required: true
    type: multiplechoice
    variable: prompt_ztp_interface
    choices: '{{PhysInts|default("")|regex_replace("^ ")|regex_replace(" ","\n")}}'
  - question_name: "Interface IP Address and CIDR Notation: (e.g. x.x.x.x/x)"
    question_description: "(optional) Configure IP address on secondary interface"
    required: false
    type: text
    variable: prompt_ztp_int_ipaddr
    min: 9
    max: 18
  - question_name: "DHCP Config - Subnet IP and Mask: (e.g. 192.168.0.0/24)"
    required: true
    type: text
    variable: prompt_ztp_dhcp_subnet
    min: 9
    max: 18
  - question_name: "DHCP Config - Subnet Range: (e.g. 192.168.0.100-192.168.0.200)"
    required: true
    type: text
    variable: prompt_ztp_dhcp_range
    min: 15
    max: 31
  - question_name: "DHCP Config - Default Router: (e.g. 192.168.0.1)"
    required: false
    type: text
    variable: prompt_ztp_dhcp_rtr
    min: 7
    max: 15
  - question_name: "Static IP Pool Config - Switch Interface:"
    question_description: "(e.g. management1, ve 20 or e1/1/1)"
    required: false
    type: text
    variable: prompt_ztp_ippool_int
    min: 2
    max: 1024
  - question_name: "Static IP Pool Config - Subnet: (e.g. 192.168.0.0/24)"
    required: false
    type: text
    variable: prompt_ztp_ippool_subnet
    min: 9
    max: 18
  - question_name: "Static IP Pool Config - IP Range: (e.g. 192.168.0.10-192.168.0.99)"
    required: false
    type: text
    variable: prompt_ztp_ippool_range
    min: 15
    max: 31
  - question_name: "Hostname Pool Config - Base Name:"
    required: false
    type: text
    variable: prompt_ztp_hostname_base
    min: 1
    max: 1024
  - '{{awxcli_prompts[0] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[1] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[2] if vNeedAwxSshCreds else []}}'


ztp_server_address_survey:
  - '{{ztp_management_survey[1]}}'
  - '{{ztp_management_survey[2]}}'
  - question_name: "IP Route - Destination Network: (e.g. x.x.x.x/x)"
    required: false
    type: text
    variable: prompt_ztp_int_destnet
    min: 9
    max: 18
  - question_name: "IP Route - Router Address: (e.g. x.x.x.x)"
    question_description: "Next hop to destination network"
    required: false
    type: text
    variable: prompt_ztp_int_rtr
    min: 7
    max: 15
  - '{{awxcli_prompts[0] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[1] if vNeedAwxSshCreds else []}}'
  - '{{awxcli_prompts[2] if vNeedAwxSshCreds else []}}'


ztp_templates:
  - name: ZTP-Regen-AuthToken
    playbook_rev: 0.1.0
    description: "Regenerate DHCP Webhook Authentication Token"
    playbook: ZTP-Management.yml
    inventory: '{{awx_inventory_id}}'
    ask_credential_on_launch: false
    ask_limit_on_launch: false
    use_fact_cache: true
    survey_spec: '{{awxcli_prompts if vNeedAwxSshCreds else ""}}'

  - name: ZTP-Configure-Server-Address
    playbook_rev: 0.1.0
    description: "Configure IP address on secondary interface"
    playbook: ZTP-Management.yml
    inventory: '{{awx_inventory_id}}'
    ask_credential_on_launch: false
    ask_limit_on_launch: false
    use_fact_cache: true
    survey_spec: '{{ztp_server_address_survey|select()|list}}'

  - name: Provisioning-Init-Login
    playbook_rev: 0.1.0
    description: "Setup ICX initial login"
    playbook: Provisioning-Init-Login.yml

  - name: Provisioning-Finalize
    playbook_rev: 0.1.0
    description: "Configure static IP and move host to final Inventory"
    playbook: Provisioning-Finalize.yml


mgmt_template_specs:
- name: AWX-Template-Management
  playbook_rev: 0.1.0
  description: "Create/update or remove templates"
  playbook: AWX-Template-Management.yml
  inventory: '{{awx_inventory_id}}'
  ask_credential_on_launch: false
  ask_limit_on_launch: false
  use_fact_cache: true
  survey_spec: '{{awx_tmplt_mgmt_survey|select()|list}}'

- name: Image-Management
  playbook_rev: 0.1.0
  description: "Create image repo, import images and create/update file list"
  playbook: Image-Management.yml
  inventory: '{{awx_inventory_id}}'
  ask_credential_on_launch: false
  ask_limit_on_launch: false
  use_fact_cache: true
  survey_spec: '{{img_mgmt_survey|select()|list}}'

- '{{image_flash_copy_templates[0] if SwImgFileList is defined else []}}'
- '{{image_flash_copy_templates[1] if SwImgVerList is defined else []}}'

- name: ZTP-Management
  playbook_rev: 0.1.0
  description: "Zero-Touch Provisioning Setup"
  playbook: ZTP-Management.yml
  inventory: '{{awx_inventory_id}}'
  ask_credential_on_launch: false
  ask_limit_on_launch: false
  use_fact_cache: true
  survey_spec: '{{ztp_management_survey|select()|list}}'


mgmt_templates: '{{mgmt_template_specs|select()|list}}'
