#! Description: Create/update or remove templates in a project.
---
- name: Create or Update Job Templates
  hosts: all
  connection: local
  gather_facts: no
  module_defaults:
    uri:
      validate_certs: '{{template_validate_certs}}'
      method: GET
      user: '{{awxlogin_user}}'
      password: '{{awxlogin_pass}}'
      force_basic_auth: yes
      timeout: 60
  vars:
    AwxMgmtVer: 1.4
    ServerVersion: '{{ansible_icx_mgmt_ver|default(0)}}'
    AwxApi: https://{{ansible_host}}/api/v2
    MgmtFunc: '{{prompt_mgmt_role|default("Management Update", true)}}'
    YamlExt: '.yml'
    NewlineVar: '\\\\n'
    template_validate_certs: no

  roles:
  - {role: awx_management}
