#! Description: Create/update or remove templates in a project.
---
- name: Create or Update Job Templates
  hosts: all
  connection: local
  gather_facts: no
  module_defaults:
    uri:
      validate_certs: '{{template_validate_certs}}'
      method: GET
      user: '{{awxlogin_user}}'
      password: '{{awxlogin_pass}}'
      force_basic_auth: yes
      timeout: 60
  vars:
    AwxApi: https://{{ansible_host}}/api/v2
    MgmtFunc: '{{prompt_mgmt_role|default("Management Update", true)}}'
    template_validate_certs: no
    PbRev: '{{playbook_rev|default("0.0.0")}}'

  roles:
  - {role: awx_management}
