---
- hosts: all
  connection: local
  gather_facts: no
  module_defaults:
    uri:
      validate_certs: '{{host_validate_certs|default(false)}}'
      method: GET
      user: '{{awxlogin_user}}'
      password: '{{awxlogin_pass}}'
      force_basic_auth: yes
      timeout: 60
  vars:
    ansible_python_interpreter: '{{ansible_playbook_python}}'
    AwxApi: https://{{ansible_host}}/api/v2
    ImgMgmtDir: '{{icx_awx_mgmt.img_mgmt.awx_image_dir|default("null")}}'
    MgmtFunc: '{{prompt_mgmt_role|default("Management Update", true)}}'
    IsAwxTmpltMgmt: true
    PbRev: '{{playbook_rev|default("0.0.0")}}'

  roles:
  - {role: awx_management}
