---
- hosts: all
  connection: local
  gather_facts: no
  vars:
    BinVerRe: '^[A-Za-z]{3,4}([0-9]{2})([0-9])([0-9]{2}[a-zA-Z]{0,2}(b[0-9]{3})?)(ufi)?.bin'
    ShVerRe: '[0-9]{2}.[0-9]{1}.[0-9]{2}[a-z]*'

  roles:
  - {role: image_management}
