---
- hosts: all
  connection: local
  gather_facts: no
  module_defaults:
    uri:
      validate_certs: '{{template_validate_certs}}'
      method: GET
      user: '{{awxlogin_user}}'
      password: '{{awxlogin_pass}}'
      force_basic_auth: yes
      timeout: 60
  vars:
    ansible_python_interpreter: '{{ansible_playbook_python}}'
    AwxApi: https://{{ansible_host}}/api/v2
    ValidFileTypes:
      - .bin
    MgmtFunc: "Image Management"
    ImgMgmtDir: "{{prompt_imgrepo_path}}"
    IsImgMgmt: true

  pre_tasks:
  - name: Check for Proper Path
    assert: {that: "ImgMgmtDir is match('^/.*')", fail_msg: 'Invalid Path'}

  roles:
  - {role: awx_management}
