---
- hosts: all
  connection: local
  gather_facts: no
  module_defaults: {wait_for: {host: '{{ansible_host}}', port: 22, timeout: 30}}
  vars:
    RebootAllowed: '{{prompt_flash_reload}}'
    BootPrefChange: '{{prompt_flash_change_boot}}'
    BootPart: '{{"sec" if prompt_flash_part|lower == "secondary" else "pri"}}'
    ScpTimeout: '{{template_flash_copy_timeout|default(300)}}'
    RebootTimeout: '{{template_flash_reload_timeout|default(600)}}'

  pre_tasks:
  - name: REST API Block
    block:
    - name: Get AWX Server Host ID
      uri:
        url: '{{bAwxApi}}/hosts/?name={{prompt_image_repo_hostname|urlencode}}'
      register: rAwxHost

    - name: Get AWX Server Host Facts
      uri: {url: '{{bAwxApi}}/hosts/{{tHostId}}/ansible_facts'}
      register: rAwxHostFacts
      vars: {tHostId: '{{rAwxHost.json.results[0].id}}'}
    vars: {bAwxApi: "https://{{prompt_image_repo_address}}/api/v2"}
    module_defaults:
      uri:
        validate_certs: '{{host_validate_certs|default(false)}}'
        method: GET
        user: '{{awxlogin_user}}'
        password: '{{awxlogin_pass}}'
        force_basic_auth: yes
        timeout: 60

  - name: Set File List Variables
    set_fact:
      ImgRepoFiles: '{{tAwxMgmt.img_mgmt.image_files|default()}}'
      ImgRepoBootFiles: '{{tAwxMgmt.img_mgmt.boot_files|default()}}'
      AwxHostInterpreter: '{{tPyInt}}'
    vars:
      tAwxMgmt: '{{rAwxHostFacts.json.icx_awx_mgmt|default()}}'
      tPyInt: '{{tAwxMgmt.ssh_interpreter|default(ansible_playbook_python)}}'

  - name: Verify Retrieval of Installed Image List
    assert:
      that: ImgRepoFiles|default("null", true) != "null"
      fail_msg:
        - "Unable to retrieve list of installed images from AWX Server"
        - "Run the 'Image-Management' or 'AWX-Template-Management'"
        - "template to rebuild image list"

  roles:
  - {role: image_flash_copy}
