# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required Variables:
# <template_l2_mstpname> MSTP Region Name
# <template_l2_mstprev> MSTP Region Revision
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Configuring MSTP
    icx_config:
      lines: |
        mstp scope pvst
        mstp name {{template_l2_mstpname}}
        mstp revision {{template_l2_mstprev}}
        mstp start
      save_when: changed
