# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required Variables:
# <template_l2_vid> VLAN ID
#
# Optional Variables:
# <template_l2_vname> VLAN name
# <tamplate_l2_vuntag> Interface to add as untagged
# <template_l2_vtag> Interface to add as tagged
# <template_l2_vnountag> Untagged interface to remove from VLAN
# <template_l2_vnotag> Tagged interface to remove from VLAN
# <template_l2_vrtr> (true|false) Create router interface. Default false
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    vlan_name:
    tagged_ports:
    untagged_ports:
    no_tagged_ports:
    no_untagged_ports:
    router_interface:

  tasks:
  - name: Checking VLAN Name
    set_fact:
      vlan_name: "name {{template_l2_vname}}"
      cacheable: no
    when: template_l2_vname is defined and template_l2_vname != ''

  - name: Checking Tagged Ports
    set_fact:
      tagged_ports: "tagged {{template_l2_vtag}}"
      cacheable: no
    when: template_l2_vtag is defined and template_l2_vtag != ''

  - name: Checking Untagged Ports
    set_fact:
      untagged_ports: "untagged {{template_l2_vuntag}}"
      cacheable: no
    when: template_l2_vuntag is defined and template_l2_vuntag != ''

  - name: Checking Tagged Ports to Remove
    set_fact:
      no_tagged_ports: "no tagged {{template_l2_vtag}}"
      cacheable: no
    when: template_l2_vnotag is defined and template_l2_vnotag != ''

  - name: Checking Untagged Ports to Remove
    set_fact:
      no_untagged_ports: "no untagged {{template_l2_vuntag}}"
      cacheable: no
    when: template_l2_vnountag is defined and template_l2_vnountag != ''

  - name: Create Virtual Ethernet Interface
    set_fact:
      router_interface: "router-interface ve {{template_l2_vid}}"
      cacheable: no
    when: template_l2_vrtr is defined and template_l2_vrtr|lower == 'true'

  - name: Configuring VLAN
    icx_config:
      lines: |
        vlan {{template_l2_vid}} {{vlan_name}}
         {{no_tagged_ports}}
         {{no_untagged_ports}}
         {{tagged_ports}}
         {{untagged_ports}}
         {{router_interface}}
      save_when: changed

  - name: Display Results
    icx_command:
      commands: show vlan {{template_l2_vid}}
    register: output
  - debug:
      msg: "{{output.stdout_lines}}"
