# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required Variables:
# <template_rtr_defv6rtr> IPv6 Address of default router
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Configuring Default IPv6 Route
    icx_config:
      lines: |
        ipv6 route ::/0 {{template_rtr_defv6rtr}}
      save_when: changed

  - name: Display Results
    icx_command:
      commands: show ipv6 route
    register: output
  - debug:
      msg: "{{output.stdout_lines}}"
