#! Description: Configure default IPv6 route.
#! Prompt: [{question_name: Default Router, question_description: Enter IPv6 address of default router@colon, required: true, type: text, variable: template_rtr_defv6rtr, min: 1, max: 1024, default: '', choices: ''}]
# =====================
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    newline_var: "\r"
    error_parse: '^.*ConnectionError: '

  tasks:
  - name: Configuring Default IPv6 Route
    icx_config: {lines: 'ipv6 route ::/0 {{template_rtr_defv6rtr}}', save_when: changed}
    register: icxconfig_status
    failed_when: icxconfig_status.msg is defined and "MODULE FAILURE" not in icxconfig_status.msg

  - name: Parse Switch Error
    set_fact:
      error_msg: "{{icxconfig_status.module_stderr|regex_replace('\n')|regex_replace(error_parse)}}"
    when: icxconfig_status.rc is defined and icxconfig_status.rc == 1

  - name: Display Switch Error
    assert: {that: error_msg is not defined, fail_msg: '{{error_msg.split(newline_var)}}'}
    when: error_msg is defined

  - name: Get Route Table
    icx_command: {commands: show ipv6 route}
    register: output

  - name: Display Route Table
    debug: var=output.stdout_lines[0]
