#! Description: Enable a disabled LAG interface.
#! Prompt: [{question_name: LAG Name, question_description: Enter LAG name@colon, required: true, type: text, variable: template_lag_name, min: 1, max: 64, default: '', choices: '', new_question: true}, {question_name: LAG Ports, question_description: Enter the LAG ports (e.g. e 1/1/1 e 1/1/2), required: true, type: text, variable: template_lag_port, min: 5, max: 1024, default: '', choices: '', new_question: true}]
# =====================
# Note: LAG-Interface-Add needs to be applied before running this template.
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    NewlineVar: "\r"
    ErrParse: '^.*ConnectionError: '
    EthRe: '(ethernet|etherne|ethern|ether|ethe|eth|et|e)'
    PortRe: '([0-9]{1,2}/[0-9]{1,2}/[0-9]{1,2})'
    RngRe: '^.*([0-9]{1,2}/[0-9]{1,2}/[0-9]{1,2}).*to.*([0-9]{1,2}/[0-9]{1,2}/[0-9]{1,2}).*$'

  tasks:
  - name: Get LAG Config
    icx_command: {commands: 'show run | include lag {{template_lag_name}}'}
    register: LagStatus

  - name: Verify LAG Config
    assert:
      that: LagStatus is defined and LagStatus.stdout[0] != ''
      fail_msg: "ERROR: LAG-Interface-Add needs to be applied before running this template"

  - name: Format Interface List
    set_fact: {EthInt: '{{tEthInt|regex_replace(PortRe, "e \1")}}'}
    vars: {tEthInt: '{{template_lag_port|regex_replace(EthRe)}}'}
    when: "'to' not in template_lag_port"

  - name: Format Interface Range
    set_fact: {EthInt: '{{template_lag_port|regex_replace(RngRe, "e \1 to \2")}}'}
    when: "'to' in template_lag_port"

  - name: Enabling LAG Interface
    icx_config:
      lines: no disable {{EthInt}}
      parents: lag {{template_lag_name}}
      save_when: changed
    register: IcxCfgStatus
    failed_when: false

  - name: Parse Switch Error
    set_fact:
      ErrMsg: "{{IcxCfgStatus.module_stderr|regex_replace('\n')|regex_replace(ErrParse)}}"
    when: IcxCfgStatus.rc is defined and IcxCfgStatus.rc == 1

  - name: Display Switch Error
    assert: {that: ErrMsg is not defined, fail_msg: '{{ErrMsg.split(NewlineVar)}}'}
    when: ErrMsg is defined

  - name: Get LAG Config
    icx_command: {commands: 'show lag {{template_lag_name}}'}
    register: LagCfg

  - {name: Display LAG Config, debug: {msg: "{{LagCfg.stdout_lines[0]}}"}}
