# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required Variables:
# <template_portsec_int> Interface to apply Port Security
#
# Optional Variables:
# <template_portsec_max> Maximum number of restricted MAC addresses
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    template_portsec_max: 1

  tasks:
  - name: Applying Port Security
    icx_config:
      lines: |
        interface {{template_portsec_int}}
         port security
          maximum {{template_portsec_max}}
          enable
      save_when: changed

  - name: Display Results
    icx_command:
      commands: show port security
    register: output
  - debug: 
      msg: "{{output.stdout_lines}}"
