#! Description: Configure strict standards for passwords.
#! Prompt: [{question_name: Minimum Password Length@colon, question_description: '', required: false, type: integer, variable: prompt_rem_pwminlength, min: 1, max: 48, default: 12, choices: ''}]
#! PlaybookVersion: 1.3
# =====================
# Note: Applies the following config:
#         enable strict-password-enforcement
#         enable password-min-length {{prompt_rem_pwminlength}}
#         enable user password-masking
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    newline_var: "\r"
    ErrParse: '^.*ConnectionError: '

  tasks:
  - name: Configure Strict Standards for Passwords
    icx_config:
      lines: |
        enable strict-password-enforcement
        enable password-min-length {{prompt_rem_pwminlength|default("1")}}
        enable user password-masking
      save_when: changed
    register: IcxCfgStatus
    failed_when:
      - IcxCfgStatus.msg is defined
      - "'MODULE FAILURE' not in IcxCfgStatus.msg"

  - name: Parse Switch Error
    set_fact:
      ErrMsg: "{{IcxCfgStatus.module_stderr|regex_replace('\n')|regex_replace(ErrParse)}}"
    when: IcxCfgStatus.rc is defined and IcxCfgStatus.rc == 1

  - name: Display Switch Error
    assert: {that: ErrMsg is not defined, fail_msg: '{{ErrMsg.split(newline_var)}}'}
    when: ErrMsg is defined
