#! Description: Disable Telnet server.
#! PlaybookVersion: 1.3
# =====================
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    newline_var: "\r"
    error_parse: '^.*ConnectionError: '

  tasks:
  - name: Disable Telnet Server
    icx_config: 
      lines: |
        no telnet server
        enable telnet password I+sJus+B33nR3v0k3d
        telnet access-group 86
        telnet access-group ipv6 NoRemoteAccess
        telnet timeout 10
        enable telnet authentication
      save_when: changed
    register: icxconfig_status
    failed_when: icxconfig_status.msg is defined and "MODULE FAILURE" not in icxconfig_status.msg

  - name: Parse Switch Error
    set_fact:
      error_msg: "{{icxconfig_status.module_stderr|regex_replace('\n')|regex_replace(error_parse)}}"
    when: icxconfig_status.rc is defined and icxconfig_status.rc == 1

  - name: Display Switch Error
    assert: {that: error_msg is not defined, fail_msg: '{{error_msg.split(newline_var)}}'}
    when: error_msg is defined

  - name: Get Telnet Config
    icx_command: {commands: show telnet config}
    register: output

  - name: Display Telnet Config
    debug: var=output.stdout_lines[0]
