# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required Variables:
# <template_rem_localuser> Local account username
# <template_rem_localpw> Local account password
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Check if Password-Masking is enabled
    icx_command:
      commands: show config | incl password-masking
    register: pwmask

  - name: Disable Password-Masking
    icx_config:
      lines: no enable user password-masking
    when: pwmask.stdout[0] is defined and pwmask.stdout[0] != ''

  - name: Configuring Local User Account
    icx_user:
      name: "{{template_rem_localuser}}"
      configured_password: "{{template_rem_localpw}}"

  - name: Re-enabling Password-Masking
    icx_config:
      lines: enable user password-masking
    when: pwmask.stdout[0] is defined and pwmask.stdout[0] != ''  

  - name: Saving Config
    icx_config:
      lines: write memory

  - name: Display Results
    icx_command:
      commands: show user
    register: output
  - debug:
      msg: "{{output.stdout_lines}}"
