#! Description: Configure the source interface for TACACS traffic.
#! Prompt: [{question_name: Source Interface@colon, question_description: (i.e. eth 1/2/2@comma management 1), required: true, type: text, variable: prompt_srcint, min: 2, max: 1024, default: ''}]
# =====================
# The <host_srcint> variable takes precedence over the <prompt_srcint> variable that
# is set by the AWX survey prompt.  The <host_srcint> variable is used to set the
# source-interface for outgoing RADIUS, TACACS, NTP, SNMP and syslog traffic.
# It can be manually defined for the host, inventory, template, etc.
#
# The management interface cannot be used as the source-interface for NTP or SNMP.
# A LAG interface cannot be used as a source-interface for SNMP.
# If the management or a LAG interface is defined in the <host_srcint> variable,
# the following variables can be used to override for the corresponding application:
# <host_snmp_srcint>: Use to set source-interface for SNMP.
# <host_ntp_srcint>: Use to set source-interface for NTP.
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    NewlineVar: "\r"
    ErrParse: '^.*ConnectionError: '

  tasks:
  - name: Set Source-Interface Variable
    set_fact: {SrcInt: '{{host_srcint|default(prompt_srcint, true)}}'}

  - name: Correct Variable Spacing
    set_fact: {SrcInt: '{{SrcInt|regex_replace("^([A-Za-z]*)","\1 ")}}'}
    when: "' ' not in prompt_srcint"

  - name: Configure TACACS Source-Interface
    icx_config: {lines: 'ip tacacs source-interface {{SrcInt}}', save_when: changed}
    register: IcxCfgStatus
    failed_when: IcxCfgStatus.msg is defined and "MODULE FAILURE" not in IcxCfgStatus.msg

  - name: Parse Switch Error
    set_fact:
      ErrMsg: "{{IcxCfgStatus.module_stderr|regex_replace('\n')|regex_replace(ErrParse)}}"
    when: IcxCfgStatus.rc is defined and IcxCfgStatus.rc == 1

  - name: Display Switch Error
    assert: {that: ErrMsg is not defined, fail_msg: '{{ErrMsg.split(NewlineVar)}}'}
    when: ErrMsg is defined
