# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required:
# <template_mgmt_client> Client IP address to allow
#
# Optional:
# <template_mgmt_service> (telnet|snmp-client|web|ip ssh)
# <template_mgmt_ipv6> (true|false) Is client address IPv6. Default false.
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    template_mgmt_ipv6: false

  tasks:
  - name: Setup for IPv6
    set_fact:
      ipv6: ipv6
      cacheable: no
    when: template_mgmt_ipv6|lower == 'true'

  - name: Adding Client to All-Client List
    icx_config:
      lines: all-client {{ipv6}} {{template_mgmt_client}}
      save_when: changed
    when: template_mgmt_service is not defined or template_mgmt_service == ''

  - name: Adding Client to Client List
    icx_config:
      lines: {{template_mgmt_service}} client {{ipv6}} {{template_mgmt_client}}
      save_when: changed
    when: template_mgmt_service is defined and template_mgmt_service != ''

  - name: Display Results
    icx_command:
      commands: show run | incl client
    register: output
  - debug: 
      msg: "{{output.stdout_lines}}"
