#! Description: Create Deny ACLs for IPv4 and IPv6
#
# Playbook Version: 1.2
# =====================
# Note: Creates deny ACLs named '86' for IPv4 and 'NoRemoteAccess' for IPv6.
#       These ACLs are required for other templates that blackhole traffic.
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    newline_var: "\r"
    ErrParse: '^.*ConnectionError: '

  tasks:
  - name: Create Deny ACLs for IPv4 and IPv6
    icx_config:
      lines: |
        ip access-list standard 86
         remark DENY ALL ACCESS
         deny any
         exit
        ipv6 access-list NoRemoteAccess
         deny ipv6 any any
      save_when: changed
    register: IcxCfgStatus
    failed_when:
      - IcxCfgStatus.msg is defined
      - "'MODULE FAILURE' not in IcxCfgStatus.msg"

  - name: Parse Switch Error
    set_fact:
      ErrMsg: "{{IcxCfgStatus.module_stderr|regex_replace('\n')|regex_replace(ErrParse)}}"
    when: IcxCfgStatus.rc is defined and IcxCfgStatus.rc == 1

  - name: Display Switch Error
    assert: {that: ErrMsg is not defined, fail_msg: '{{ErrMsg.split(newline_var)}}'}
    when: ErrMsg is defined

  - name: Get Deny ACLs
    icx_command:
      commands: |
        show ip access-list 86
        show ipv6 access-list NoRemoteAccess
    register: DenyAccessLists

  - name: Display Deny ACLs
    debug: var=DenyAccessLists.stdout_lines[0]
