# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required Variables:
# <template_remote_enablepw> Enable password
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Configuring Enable Password
    icx_config:
      lines: enable super-user-password {{template_remote_enablepw}}
      save_when: changed
