# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
# <template_log_srcint> IP address of source interface
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Configuring Syslog
    icx_config:
      lines: ip syslog source-interface {{template_log_srcint}}
      save_when: changed
