# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
# <template_log_buffer> Number of max lines to store
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Configuring Syslog
    icx_config:
      lines: logging buffered {{template_log_buffer}}
      save_when: changed
