#! Description: Configure the source interface for network time queries.
#! Prompt: [{question_name: Source Interface, question_description: Type the NTP source interface. (example@colon ethe 1/2/1), required: true, type: textarea, variable: template_ntp_srcint, min: 0, max: 4096, default: host_srcint, choices: ''}]
# Playbook Version: 1.2
# =====================
# Note: The variable will need to be defined with a space between the interface type and number.
# (i.e. ethe 1/2/1, ve 100)
# 
# The following variables can be used to set the NTP source interface.
# They are listed in order of precedence (higher overrides lower).
# 
# <host_ntp_srcint>: Define at the Inventory Host. Only defines the NTP source interface for the host.
# <host_srcint>: Define at the Inventory Host.  Define source interface for all services.  Valid interface types: (ethernet|loopback|ve)
# <prompt_ntp_inttype> & <prompt_ntp_intnum>: Defined with job template Survey Prompt.
# <template_ntp_srcint>: Set at template to configure all inventory hosts with the same source interface
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    newline_var: "\r"
    error_parse: '^.*ConnectionError: '

  tasks:
  - name: Use 'host_ntp_srcint' Variable
    set_fact: {ntp_srcint: "{{host_ntp_srcint}}"}
    when: host_ntp_srcint is defined

  - name: Use 'host_srcint' Variable
    set_fact: {ntp_srcint: "{{host_srcint}}"}
    when: host_srcint is defined and ntp_srcint is not defined

  - name: Use AWX Survey Prompt Variables
    set_fact: {ntp_srcint: "{{prompt_ntp_inttype}} {{prompt_ntp_intnum}}"}
    when: prompt_ntp_inttype is defined and prompt_ntp_intnum is defined and ntp_srcint is not defined

  - name: Use 'template_ntp_srcint' Variable
    set_fact: {ntp_srcint: "{{template_ntp_srcint}}"}
    when: template_ntp_srcint is defined and ntp_srcint is not defined

  - name: Check Variable
    assert: {that: ntp_srcint is defined, fail_msg: "No variable defined"}

  - name: Validate Variable Syntax
    assert:
      that: "' ' in ntp_srcint"
      fail_msg: "There needs to be a space between the interface type and number (i.e. ethe 1/1/1)"

  - name: Configure NTP Source Interface
    icx_config:
      lines: source-interface {{ntp_srcint}}
      parents: ntp
      save_when: changed
    register: icxconfig_status
    failed_when: icxconfig_status.msg is defined and "MODULE FAILURE" not in icxconfig_status.msg

  - name: Parse Switch Error
    set_fact:
      error_msg: "{{icxconfig_status.module_stderr|regex_replace('\n')|regex_replace(error_parse)}}"
    when: icxconfig_status.rc is defined and icxconfig_status.rc == 1

  - name: Display Switch Error
    assert: {that: error_msg is not defined, fail_msg: '{{error_msg.split(newline_var)}}'}
    when: error_msg is defined
