# Playbook Version: 1.1
# =====================
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Securing Console Access
    icx_config:
      lines: |
        enable aaa console
        console timeout 10
      save_when: changed
