# Playbook Version: 1.1
# =====================
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Configuring Syslog
    icx_config:
      lines: logging console
      save_when: changed
