# Playbook Version: 1.1
# =====================
# The following variables will need to be defined prior to running this playbook:
#
# Required Variables:
# <template_qos_int> Interface to set DSCP Trust
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Setting QoS Trust on Interface
    icx_config:
      lines: |
        interface {{template_qos_int}}
         trust dscp
      save_when: changed
