#! Description: Apply login banner(s).
#! Prompt: [{question_name: Banner Connection(s)@colon, required: true, type: multiselect, variable: prompt_banner_conn, default: motd\nexec\nincoming, choices: motd\nexec\nincoming}, {question_name: Banner Text@colon, required: true, type: textarea, variable: prompt_banner_text, min: 1, max: 2556}]
# =====================
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Apply Banner
    icx_banner: {banner: '{{item}}', text: "{{prompt_banner_text}}"}
    loop: '{{prompt_banner_conn}}'

  - name: Write Memory
    icx_command: {commands: write memory}
