---
- hosts: all
  connection: local
  gather_facts: no
  module_defaults:
    uri:
      validate_certs: '{{host_validate_certs|default(false)}}'
      method: GET
      user: '{{awxlogin_user}}'
      password: '{{awxlogin_pass}}'
      force_basic_auth: yes
      timeout: 60
  vars:
    AwxApi: https://{{ansible_host}}/api/v2
    PhysInts:
    DhcpSubnetRouter:
    MgmtFunc: ZTP Management
    ZtpDefPassword: 'PasswordPassword'
    IsZtpRT: '{{this_jt_name == "ZTP-Regen-AuthToken"}}'

  roles:
  - {role: awx_management}
