#! Description: Install required ZTP components.
# =====================
# This template performs the following tasks on first run:
# - Installs 'netaddr' ansible module
# - Creates AWX application entry for 'isc-dhcp-server'
# - Generates Auth Token used by DHCP webhook.
# - Installs 'isc-dhcp-server'
# - Creates and installs 'awx-dhcp-webhook' from template
# - Creates a default ICX credential set
# - Creates 'ZTP-Configure' template
# - Creates 'ZTP-Regen-AuthToken' template
---
- hosts: all
  connection: ssh
  gather_facts: no
  module_defaults:
    uri:
      validate_certs: '{{template_validate_certs}}'
      method: GET
      user: '{{awxlogin_user}}'
      password: '{{awxlogin_pass}}'
      force_basic_auth: yes
      timeout: 60
  vars:
    AwxApi: https://{{ansible_host}}/api/v2
    template_validate_certs: no
    PhysInts:
    DhcpSubnetRouter:
    ZtpDefPassword: 'PasswordPassword'

  roles:
  - {role: common}
  - {role: ztp_install, when: ZtpParams.ZtpInstall|bool}
  - {role: ztp_config, when: ZtpParams.ZtpConfigure|bool}
  - {role: create_templates, when: TemplateCreateParams is defined}
