---
- name: Manually set path to Python Interpreter
  set_fact: {discovered_interpreter_python: /usr/bin/python3, cacheable: true}
  when: "'platform-python' in discovered_interpreter_python"

- name: Get This Template Info
  uri: {url: '{{AwxApi}}/job_templates/{{awx_job_template_id}}/'}
  register: ThisTemplate

- name: Get List of Projects
  uri: {url: '{{AwxApi}}/projects/'}
  register: PjInfo

- name: Add First Project to List
  set_fact: {ProjectList: '{{PjInfo.json.results[idx].name}}', FirstPjIdx: '{{idx}}'}
  loop: '{{range(0, PjInfo.json.count)|list}}'
  loop_control: {index_var: idx}
  when:
    - PjInfo.json.count > 1
    - PjInfo.json.results[idx].id != ThisTemplate.json.project
    - ProjectList is not defined

- name: Add Remaining Projects to List
  set_fact: {ProjectList: '{{ProjectList}}@NL@{{PjInfo.json.results[idx].name}}'}
  loop: '{{range(0, PjInfo.json.count)|list}}'
  loop_control: {index_var: idx}
  when:
    - ProjectList is defined
    - PjInfo.json.results[idx].id != ThisTemplate.json.project
    - idx != FirstPjIdx

- name: Create New Survey Prompt Payload
  set_fact:
    PromptPayload:
      name: ''
      description: ''
      spec:
      - question_name: 'Template management function:'
        required: false
        type: multiplechoice
        variable: prompt_mgmt_role
        choices: |-
          Create/Update Templates
          Remove Templates
      - question_name: 'Project:'
        required: false
        type: multiplechoice
        variable: prompt_project_name
        choices: '{{ProjectList|regex_replace("@NL@","\n")|default("")}}'

- name: Create Survey Prompt
  uri:
    url: '{{AwxApi}}/job_templates/{{awx_job_template_id}}/survey_spec/'
    method: POST
    headers: {Content-Type: 'application/json'}
    body: '{{PromptPayload}}'
    body_format: json

- name: Update Template
  uri:
    url: '{{AwxApi}}/job_templates/{{awx_job_template_id}}/'
    method: PATCH
    headers: {Content-Type: "application/json"}
    body: {extra_vars: , survey_enabled: true, use_fact_cache: true}
    body_format: json

- name: Display Update Message and Exit
  block:
    - name: Set AWX Management Version
      set_fact: {ansible_icx_mgmt_ver: '{{AwxMgmtVer}}', cacheable: yes}

    - name: Update Message
      debug:
        msg:
          - "Template updated to version {{AwxMgmtVer}}."
          - "Relaunch template to continue."

    - {name: Ending Play, meta: end_play}
  vars:
    NoMgmtPrompt: '{{prompt_mgmt_role is not defined}}'
    NoPjPrompt: '{{prompt_project_name is not defined}}'
    TemplateUpdate: '{{ServerVersion is version(AwxMgmtVer, "<")}}'
  when: TemplateUpdate|bool or NoMgmtPrompt|bool or NoPjPrompt|bool
