- name: Reload Device
  block:
  - name: Issue Reload Command
    icx_command: {commands: 'boot system flash {{BootPart}} yes'}
    register: ReloadResult
    failed_when: false

  - name: Pause If Error Returned
    wait_for: {timeout: 30}
    when: ReloadResult.stdout[0] is defined and
          "Error" in ReloadResult.stdout[0]

  - name: Reload Command Accepted
    set_fact: {ReloadSuccess: true}
    when: (ReloadResult.stdout[0] is defined and
          "Error" not in ReloadResult.stdout[0]) or
          (ReloadResult.msg is defined and
          "command timeout triggered" in ReloadResult.msg)
  when: ReloadSuccess is not defined or not ReloadSuccess|bool
