---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    newline_var: "\r"
    error_parse: '^.*ConnectionError: '
    OspfAuthCmd:
    PassiveIntCmd:

  tasks:
  - name: Get Router OSPFv3 Config
    icx_command: {commands: show run | include ^ipv6 router ospf}
    register: OspfConfig

  - name: Verify Router OSPFv3 Config
    assert:
      that:
        - OspfConfig.stdout[0] is defined
        - OspfConfig.stdout[0] != ''
      fail_msg:
        - "ERROR: IPv6 Router OSPF not configured!"
        - "L3-IPv6-OSPFGlobal needs to be applied before running this template"

  - name: Get OSPFv3 Area Config
    icx_command: {commands: 'show ipv6 ospf area {{prompt_rtr_ospfv3_area}}'}
    register: OspfConfig

  - name: Verify Configuration of OSPFv3 Area
    assert:
      that:
        - OspfConfig.stdout[0] is defined
        - OspfConfig.stdout[0] != 'No such area available'
      fail_msg:
        - "ERROR: OSPFv3 area {{prompt_rtr_ospfv3_area}} does not exist"
        - "Create OSPFv3 area {{prompt_rtr_ospfv3_area}} with L3-IPv6-OSPFGlobal template"

  - name: Set OSPFv3 Authentication Command
    set_fact:
      OspfAuthCmd: "ipv6 ospf authentication ipsec spi {{prompt_rtr_ospfv3_ipsec_spi}} esp sha1 {{prompt_rtr_ospfv3_ipsec_key}}"
    when:
      - prompt_rtr_ospfv3_ipsec_key is defined
      - prompt_rtr_ospfv3_ipsec_spi is defined
      - prompt_rtr_ospfv3_ipsec_key != ''
      - prompt_rtr_ospfv3_ipsec_spi != ''

  - name: Set OSPFv3 Passive Interface Command
    set_fact: {PassiveIntCmd: "ipv6 ospf passive"}
    when: prompt_rtr_ospfv3_passive is defined and prompt_rtr_ospfv3_passive|bool

  - name: Apply OSPFv3 Interface Config
    icx_config:
      lines: |
         ipv6 ospf area {{prompt_rtr_ospfv3_area}}
         ipv6 ospf retransmit-interval {{prompt_rtr_ospfv3_retrans|default("5")}}
         ipv6 ospf transmit-delay {{prompt_rtr_ospfv3_transdelay|default("1")}}
         {{OspfAuthCmd}}
         {{PassiveIntCmd}}
      parents: int {{prompt_rtr_int}}
      save_when: changed
    register: icxconfig_status
    failed_when: false

  - name: Parse Switch Error
    set_fact:
      error_msg: "{{icxconfig_status.module_stderr|regex_replace('\n')|regex_replace(error_parse)}}"
    when: icxconfig_status.rc is defined and icxconfig_status.rc == 1

  - name: Display Switch Error
    assert: {that: error_msg is not defined, fail_msg: '{{error_msg.split(newline_var)}}'}
    when: error_msg is defined

  - name: Get OSPF Interface Info
    icx_command: {commands: 'show ipv6 ospf interface {{prompt_rtr_int}}'}
    register: output

  - name: Display OSPF Info
    debug: var=output.stdout_lines[0]
