---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    newline_var: "\r"
    ErrParse: '^.*ConnectionError: '
    ipv6:

  tasks:
  - name: Get Service Count
    set_fact: {SvcLstCnt: '{{prompt_mgmt_service|length}}'}

  - name: Setup for IPv6
    set_fact: {ipv6: 'ipv6 '}
    when: "':' in prompt_mgmt_clientip"

  - name: Add Client IP to Service's Client List
    icx_config: {lines: '{{item}} {{ipv6}}{{prompt_mgmt_clientip}}', save_when: changed}
    register: IcxCfgStatus
    failed_when:
      - IcxCfgStatus.results[idx].msg is defined
      - "'MODULE FAILURE' not in IcxCfgStatus.results[idx].msg"
    loop: '{{prompt_mgmt_service}}'
    loop_control: {index_var: idx}

  - name: Parse Switch Error
    set_fact:
      ErrMsg: "{{IcxCfgStatus.results[idx].module_stderr|regex_replace('\n')|regex_replace(ErrParse)}}"
    loop: '{{prompt_mgmt_service}}'
    loop_control: {index_var: idx}
    when:
      - IcxCfgStatus.results[idx].rc is defined
      - IcxCfgStatus.results[idx].rc == 1

  - name: Display Switch Error
    assert: {that: ErrMsg is not defined, fail_msg: '{{ErrMsg.split(newline_var)}}'}
    when: ErrMsg is defined
