#! Prompt: [{question_name: Primary Authentication Method@colon, question_description: '', required: true, type: multiplechoice, variable: prompt_aaa_prim, min: null, max: null, default: '', choices: enable\nline\nlocal\nnone\nradius\ntacacs\ntacacs+}, {question_name: Secondary Authentication Method, question_description: Optional. Can be left blank., required: false, type: multiplechoice, variable: prompt_aaa_sec, min: null, max: null, default: '', choices: enable\nline\nlocal\nnone\nradius\ntacacs\ntacacs+}]
# =====================
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    NewlineVar: "\r"
    ErrParse: '^.*ConnectionError: '

  tasks:
  - name: Configure AAA Authentication
    icx_config:
      lines: |
        aaa authentication enable default {{prompt_aaa_prim}} {{prompt_aaa_sec|default()}}
        aaa authentication login default {{prompt_aaa_prim}} {{prompt_aaa_sec|default()}}
        aaa authentication login privilege-mode
      save_when: changed
    register: IcxCfgStatus
    failed_when: IcxCfgStatus.msg is defined and "MODULE FAILURE" not in IcxCfgStatus.msg

  - name: Parse Switch Error
    set_fact:
      ErrMsg: "{{IcxCfgStatus.module_stderr|regex_replace('\n')|regex_replace(ErrParse)}}"
    when: IcxCfgStatus.rc is defined and IcxCfgStatus.rc == 1

  - name: Display Switch Error
    assert: {that: ErrMsg is not defined, fail_msg: '{{ErrMsg.split(NewlineVar)}}'}
    when: ErrMsg is defined
