---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Apply Banner
    icx_banner: {banner: '{{item}}', text: "{{prompt_banner_text}}"}
    loop: '{{prompt_banner_conn}}'

  - name: Write Memory
    icx_command: {commands: write memory}
