#! Description: Disable NTP MD5 Authentication.
# =====================
---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable

  tasks:
  - name: Disabling MD5 NTP Authentication
    icx_config:
      lines: disable authenticate md5
      parents: ntp
      save_when: changed
