---
- hosts: all
  connection: network_cli
  gather_facts: no
  vars:
    ansible_network_cli_ssh_type: paramiko
    ansible_network_os: icx
    ansible_become: true
    ansible_become_method: enable
    NewlineVar: "\r"
    ErrParse: '^.*ConnectionError: '

  tasks:
  - name: Setup for Disabling Severity Level
    set_fact: {SevDisable: "no logging buffered"}
    when: prompt_log_level_enable == "Disable"

  - name: Configure Syslog Facility
    icx_config:
      lines: '{{SevDisable|default("logging buffered", true)}} {{prompt_log_level}}'
      save_when: changed
    register: IcxCfgStatus
    failed_when:
      - IcxCfgStatus.msg is defined
      - "'MODULE FAILURE' not in IcxCfgStatus.msg"

  - name: Parse Switch Error
    set_fact:
      ErrMsg: "{{IcxCfgStatus.module_stderr|regex_replace('\n')|regex_replace(ErrParse)}}"
    when: IcxCfgStatus.rc is defined and IcxCfgStatus.rc == 1

  - name: Display Switch Error
    assert: {that: ErrMsg is not defined, fail_msg: '{{ErrMsg.split(NewlineVar)}}'}
    when: ErrMsg is defined
