---
- name: Debug
  debug: msg="Creating template '{{PbFileName|regex_replace(YamlExt)}}'"

- name: Create Template
  uri:
    url: '{{AwxApi}}/job_templates/'
    method: POST
    headers: {Content-Type: "application/json"}
    body: "{{tTemplateStruct}}"
    body_format: json
    status_code: 201
  register: NewJobTemplate
  vars:
    tTemplateStruct:
      name: '{{PbFileName|regex_replace(YamlExt)}}'
      project: '{{PjId}}'
      playbook: '{{PbFileName}}'
      ask_credential_on_launch: true
      ask_inventory_on_launch: '{{prompt_ask_inventory_on_launch|default(true)}}'
      ask_limit_on_launch: true

- name: Update Templates
  include_tasks: update_template.yml
  vars: {TemplateId: '{{NewJobTemplate.json.id}}', ExtraVars: 'template_version: 0.0'}
