---
- name: Create Boot File Info List
  set_fact:
    BootImgList: '{{BootImgList|default([])}} + {{tBootFileInfo}}'
    BootFileNames: "{{BootFileNames|default('None\nAuto Select\n')}}{{bImgFileName}}\n"
  vars:
    tBootFileInfo:
    - filename: '{{bImgFileName}}'
      path: '{{bImgFilePath}}'
      software_version: '{{bBinImgVer}}'
      supported_platforms: '{{BootcodePlatformSupport[bPlatCode]}}'
  when: BootcodePlatformSupport[bPlatCode] is defined and
        (bImgCode == "Z" or bImgCode == "U")

- name: Create Image File Info List
  block:
  - name: Create and Add File Entry to List
    set_fact:
      SwImgList: '{{SwImgList|default([])}} + {{tSwImgInfo}}'
      SwImgFileList: "{{SwImgFileList|default()}}{{bImgFileName}}\n"
      SwImgVerList: '{{SwImgVerList|default([])}} + {{[bBinImgVer]}}'
    vars:
      tImgDir: '{{ImgMgmtDir}}'
      tImgType: '{{"router" if bImgCode == "R" else "switch"}}'
      tImdFileRe: "{{tImgDir}}/{{bPlatCode}}{{bImgCode}}08080[a-zA-Z]{0,2}.bin"
      tImdImgList: '{{bImgFileList|select("match", tImdFileRe)|list}}'
      tImdImgReq: '{{bBinImgVer is version("08.0.90", ">=")}}'
      tBootVer: '{{(BootToImageVer|rejectattr("img_ver_min", ">", bBinImgVer)
                                  |rejectattr("img_ver_max", "<", bBinImgVer)
                                  |list|last).boot_version|default()}}'
      tPS: '{{SoftwarePlatformSupport[bPlatCode]
             |rejectattr(tImgType~"_min_ver", "undefined")
             |selectattr(tImgType~"_min_ver", "<=", bBinImgVer)|list}}'
      tSuppPlat: '{{tPS|rejectattr("ufi_only")|list if not bIsUfi else tPS}}'
      tSwImgInfo:
      - filename: '{{bImgFileName}}'
        img_type: '{{tImgType}}'
        is_ufi: '{{bIsUfi}}'
        path: '{{bImgFilePath}}'
        software_version: '{{bBinImgVer}}'
        supported_platforms: '{{tSuppPlat|map(attribute="platform")|flatten|sort}}'
        supported_bootrom_ver: '{{tBootVer|default() if not bIsUfi else ""}}'
        intermediate_image: '{{tImdImgList[0]|default() if tImdImgReq else ""}}'
    when: tSuppPlat|default("null", true) != "null"
  when: SoftwarePlatformSupport[bPlatCode] is defined and
        (bImgCode == "R" or bImgCode == "S")
