- name: Create Directory or Find Image Files
  block:
  - name: Create Directory for Image Repo in Projects Directory
    file:
      path: '{{ImgMgmtRepoDir}}'
      owner: '{{ansible_user}}'
      group: '{{ansible_user}}'
      state: directory
    vars:
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_password: '{{awxssh_sudo|default(prompt_awxcli_sudo)
                                             |default(prompt_awxcli_pass)}}'
    when: IsImgMgmt|default(false)

  - name: Search for Binary Files in Repo
    find: {paths: '{{ImgMgmtRepoDir}}', recurse: yes, patterns: '*.bin'}
    register: rImgFiles
  connection: ssh
  vars:
    ansible_python_interpreter: '{{icx_awx_mgmt.ssh_interpreter}}'
    ansible_user: '{{awxssh_user|default(prompt_awxcli_user)}}'
    ansible_ssh_pass: '{{awxssh_pass|default(prompt_awxcli_pass)}}'

- name: Create File Lists
  block:
  - {name: Load Platform Table, include_vars: im_platform_support_table.yml}

  - name: Populate Image Table
    include_tasks: im_create_file_entry.yml
    loop: '{{bImgFileList}}'
    loop_control: {loop_var: bImgFilePath, index_var: idx}
    vars:
      bImgFileName: '{{bImgFilePath|basename}}'
      bImgFileList: '{{rImgFiles.files|map(attribute="path")|flatten|sort()}}'
      bPlatCode: '{{bImgFileName|regex_replace(regx_plat_code, "\1")|upper}}'
      bBinImgVer: '{{bImgFileName|regex_replace(regx_bin_ver, "\1.\2.\3")}}'
      bImgCode: '{{bImgFileName|regex_replace(regx_image_code, "\1")|upper}}'
      bIsUfi: "{{'ufi' in bImgFileName|lower}}"
    when: SoftwarePlatformSupport[bPlatCode] is defined or
          BootcodePlatformSupport[bPlatCode] is defined
  when: rImgFiles.files is defined

- name: Store File List and Create Utility Templates
  block:
  - name: Store IP Address of AWX Server
    set_fact: {RemoteServerIp: '{{ansible_host}}'}
    register: AwxSvrIp

  - name: Store File Entry List in AWX Host Facts
    set_fact: {ansible_image_repo_files: '{{SwImgList}}', cacheable: yes}
    register: ImgRepoFileList

  - name: Store Boot File Entry List in AWX Host Facts
    set_fact: {ansible_image_repo_boot_files: '{{BootImgList|default()}}', cacheable: yes}
    register: ImgRepoBootFileList

  - name: Create Vars File in Repo Directory
    block:
    - name: Create Path for File Entry Variable File
      file:
        path: '{{ImgMgmtRepoDir}}/host_vars'
        state: directory

    - name: Create File Entry Variable File in Image Repo Directory
      template:
        src: all.yml.j2
        dest: '{{ImgMgmtRepoDir}}/host_vars/all.yml'
        mode: 0644
    connection: ssh
    vars:
      ansible_python_interpreter: '{{icx_awx_mgmt.ssh_interpreter}}'
      ansible_user: '{{awxssh_user|default(prompt_awxcli_user)}}'
      ansible_ssh_pass: '{{awxssh_pass|default(prompt_awxcli_pass)}}'
  when: SwImgList is defined
