- name: Create Directory or Find Image Files
  block:
  - name: Create Directory for Image Repo in Projects Directory
    file:
      path: '{{ImgMgmtRepoDir}}'
      owner: '{{ansible_user}}'
      group: '{{ansible_user}}'
      state: directory
    vars:
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_password: '{{awxssh_sudo|default(prompt_awxcli_sudo)
                                             |default(prompt_awxcli_pass)}}'
    when: IsImgMgmt|default(false)

  - name: Search for Binary Files in Repo
    find: {paths: '{{ImgMgmtRepoDir}}', recurse: yes, patterns: '*.bin'}
    register: rImgFiles
  connection: ssh
  vars:
    ansible_python_interpreter: '{{icx_awx_mgmt.ssh_interpreter}}'
    ansible_user: '{{awxssh_user|default(prompt_awxcli_user)}}'
    ansible_ssh_pass: '{{awxssh_pass|default(prompt_awxcli_pass)}}'

- name: Create File Lists
  block:
  - {name: Load Platform Table, include_vars: im_platform_support_table.yml}

  - name: Populate Image Table
    include_tasks: im_create_file_entry.yml
    loop: '{{bImgFileList}}'
    loop_control: {loop_var: bImgFilePath, index_var: idx}
    vars:
      bImgFileName: '{{bImgFilePath|basename}}'
      bImgFileList: '{{rImgFiles.files|map(attribute="path")|flatten|sort()}}'
      bPlatCode: '{{bImgFileName|regex_replace(regx_plat_code, "\1")|upper}}'
      bBinImgVer: '{{bImgFileName|regex_replace(regx_bin_ver, "\1.\2.\3")}}'
      bImgCode: '{{bImgFileName|regex_replace(regx_image_code, "\1")|upper}}'
      bIsUfi: "{{'ufi' in bImgFileName|lower}}"
    when: SoftwarePlatformSupport[bPlatCode] is defined or
          BootcodePlatformSupport[bPlatCode] is defined

  - name: Cache File Entry Lists
    set_fact: {icx_awx_mgmt: '{{icx_awx_mgmt|combine(tImg)}}', cacheable: true}
    vars:
      tImg:
        img_mgmt:
          awx_image_dir: '{{ImgMgmtRepoDir}}'
          image_files: '{{SwImgList}}'
          boot_files: '{{BootImgList|default()}}'
  when: rImgFiles.files|default("null", true) != "null"
