- name: Create Directory or Find Image Files
  block:
  - name: Create Directory for Image Repo in Projects Directory
    file:
      path: '{{ImgMgmtRepoDir}}'
      owner: '{{ansible_user}}'
      group: '{{ansible_user}}'
      state: directory
    vars:
      ansible_become: true
      ansible_become_method: sudo
      ansible_become_password: '{{awxssh_sudo|default(prompt_awxcli_sudo)
                                             |default(prompt_awxcli_pass)}}'
    when: IsImgMgmt|default(false)

  - name: Search for Binary Files in Repo
    find: {paths: '{{ImgMgmtRepoDir}}', recurse: yes, patterns: '*.bin'}
    register: rImgFiles
  connection: ssh
  vars:
    ansible_python_interpreter: '{{icx_awx_mgmt.ssh_interpreter}}'
    ansible_user: '{{awxssh_user|default(prompt_awxcli_user)}}'
    ansible_ssh_pass: '{{awxssh_pass|default(prompt_awxcli_pass)}}'

- name: Create File Lists
  block:
  - {name: Load Platform Table, include_vars: im_platform_support_table.yml}

  - name: Populate Image Table
    include_tasks: im_create_file_entry.yml
    loop: '{{bImgFileList}}'
    loop_control: {loop_var: bImgFilePath, index_var: idx}
    vars:
      bImgFileName: '{{bImgFilePath|basename}}'
      bImgFileList: '{{rImgFiles.files|map(attribute="path")|flatten|sort()}}'
  when: rImgFiles.files is defined

- name: Store File List and Create Utility Templates
  block:
  - name: Store IP Address of AWX Server
    set_fact: {RemoteServerIp: '{{ansible_host}}'}
    register: AwxSvrIp

  - name: Store File Entry List in AWX Host Facts
    set_fact: {ansible_image_repo_files: '{{SwImgList}}', cacheable: yes}
    register: ImgRepoFileList

  - name: Store Boot File Entry List in AWX Host Facts
    set_fact: {ansible_image_repo_boot_files: '{{BootImgList|default()}}', cacheable: yes}
    register: ImgRepoBootFileList

  - name: Create Vars File in Repo Directory
    block:
    - name: Create Path for File Entry Variable File
      file:
        path: '{{ImgMgmtRepoDir}}/host_vars'
        state: directory

    - name: Create File Entry Variable File in Image Repo Directory
      template:
        src: all.yml.j2
        dest: '{{ImgMgmtRepoDir}}/host_vars/all.yml'
        mode: 0644
    connection: ssh
    vars:
      ansible_python_interpreter: '{{icx_awx_mgmt.ssh_interpreter}}'
      ansible_user: '{{awxssh_user|default(prompt_awxcli_user)}}'
      ansible_ssh_pass: '{{awxssh_pass|default(prompt_awxcli_pass)}}'

  - name: Get This Template Info
    uri: {url: '{{AwxApi}}/job_templates/{{awx_job_template_id}}/'}
    register: ThisTemplate

  - name: Check For Existing 'Image-Flash-Copy' Template
    uri: {url: '{{AwxApi}}/job_templates/?name=Image-Flash-Copy'}
    register: ImgFlCpTemplate

  - name: Check For Existing 'Image-Flash-Copy-File' Template
    uri: {url: '{{AwxApi}}/job_templates/?name=Image-Flash-Copy-File'}
    register: ImgFlCpFileTemplate

  - name: Check For Existing 'Image-Flash-Copy-Version' Template
    uri: {url: '{{AwxApi}}/job_templates/?name=Image-Flash-Copy-Version'}
    register: ImgFlCpVerTemplate

  - name: Rename 'Image-Flash-Copy' Template
    uri:
      url: '{{AwxApi}}/job_templates/{{ImgFlCpTemplate.json.results[0].id}}/'
      method: PATCH
      headers: {Content-Type: "application/json"}
      body: {name: "Image-Flash-Copy-File"}
      body_format: json
    when: ImgFlCpTemplate.json.count > 0 and
          ImgFlCpFileTemplate.json.count == 0

  - name: Store 'Image-Flash-Copy' Template Info
    set_fact: {CopyFileTemplateInfo: '{{ImgFlCpTemplate.json.results[0]}}'}
    when: ImgFlCpTemplate.json.count > 0

  - name: Store 'Image-Flash-Copy-File' Template Info
    set_fact: {CopyFileTemplateInfo: '{{ImgFlCpFileTemplate.json.results[0]}}'}
    when: ImgFlCpFileTemplate.json.count > 0

  - name: Store 'Image-Flash-Copy-Version' Template Info
    set_fact: {CopyVerTemplateInfo: '{{ImgFlCpVerTemplate.json.results[0]}}'}
    when: ImgFlCpVerTemplate.json.count > 0

  - name: Create 'Image-Flash-Copy-File' Template
    block:
    - name: Create 'Image-Flash-Copy-File' Template
      uri:
        url: '{{AwxApi}}/job_templates/'
        method: POST
        headers: {Content-Type: "application/json"}
        body:
          name: Image-Flash-Copy-File
          description: "Copy file(s) to switch"
          project: '{{ThisTemplate.json.project}}'
          playbook: Image-Management.yml
          ask_limit_on_launch: true
          ask_inventory_on_launch: true
          ask_credential_on_launch: true
        body_format: json
        status_code: 201
      register: NewImgFlCpFileTemplate

    - name: Store 'Image-Flash-Copy-File' Template Info
      set_fact: {CopyFileTemplateInfo: '{{NewImgFlCpFileTemplate.json}}'}
    when: ImgFlCpTemplate.json.count == 0 and
          ImgFlCpFileTemplate.json.count == 0

  - name: Create 'Image-Flash-Copy-Version' Template
    block:
    - name: Create 'Image-Flash-Copy-Version' Template
      uri:
        url: '{{AwxApi}}/job_templates/'
        method: POST
        headers: {Content-Type: "application/json"}
        body:
          name: Image-Flash-Copy-Version
          description: "Update switch(es) to selected version"
          project: '{{ThisTemplate.json.project}}'
          playbook: Image-Management.yml
          ask_limit_on_launch: true
          ask_inventory_on_launch: true
          ask_credential_on_launch: true
        body_format: json
        status_code: 201
      register: NewImgFlCpVerTemplate

    - name: Store 'Image-Flash-Copy-Version' Template Info
      set_fact: {CopyVerTemplateInfo: '{{NewImgFlCpVerTemplate.json}}'}
    when: ImgFlCpVerTemplate.json.count == 0

  - {name: Sort List, set_fact: {SwImgVerList: "{{SwImgVerList|unique|sort|join('\n')}}"}}
  - {name: Load Survey Spec Variables, include_vars: img_fl_cp_surveys.yml}

  - name: Add Survey Prompts for AWX SSH Credential Input
    set_fact:
      SurveyCpByFile: '{{SurveyCpByFile + SshCredSurvey}}'
      SurveyCpByVer: '{{SurveyCpByVer + SshCredSurvey}}'
    when: not PexpectStatus.changed|bool and PexpectStatus.skipped is not defined

  - name: Create 'Image-Flash-Copy-File' Survey Prompt
    uri:
      url: '{{AwxApi}}/job_templates/{{CopyFileTemplateInfo.id}}/survey_spec/'
      method: POST
      headers: {Content-Type: 'application/json'}
      body:
        name: ''
        description: ''
        spec: '{{SurveyCpByFile}}'
      body_format: json

  - name: Create 'Image-Flash-Copy-Ver' Survey Prompt
    uri:
      url: '{{AwxApi}}/job_templates/{{CopyVerTemplateInfo.id}}/survey_spec/'
      method: POST
      headers: {Content-Type: 'application/json'}
      body:
        name: ''
        description: ''
        spec: '{{SurveyCpByVer}}'
      body_format: json

  - name: Enable 'Image-Flash-Copy-File' Survey Prompt
    uri:
      url: '{{AwxApi}}/job_templates/{{CopyFileTemplateInfo.id}}/'
      method: PATCH
      headers: {Content-Type: "application/json"}
      body:
        survey_enabled: true
        extra_vars: >-
          template_image_repo_dir: {{ImgMgmtRepoDir}}
      body_format: json

  - name: Enable 'Image-Flash-Copy-Ver' Survey Prompt
    uri:
      url: '{{AwxApi}}/job_templates/{{CopyVerTemplateInfo.id}}/'
      method: PATCH
      headers: {Content-Type: "application/json"}
      body:
        survey_enabled: true
        extra_vars: >-
          template_image_repo_dir: {{ImgMgmtRepoDir}}
      body_format: json
  when: SwImgList is defined
