---
- {name: Common Tasks, include_tasks: am_common.yml}

- name: Manually set path to Python Interpreter
  set_fact: {discovered_interpreter_python: /usr/bin/python3, cacheable: true}
  when: discovered_interpreter_python is not defined or "'platform-python' in discovered_interpreter_python"

- {name: Template Management, include_tasks: template_management.yml}

- name: Job Status
  debug:
    msg:
      - "Management Function: {{MgmtFunc|default('unspecified')}}"
      - "========================"
      - ""
      - "Job Templates Created: {{CreatedTemplates|default([])|count}}"
      - "========================"
      - "{{CreatedTemplates|default()}}"
      - "Job Templates Updated: {{UpdatedTemplates|default([])|count}}"
      - "========================"
      - "{{UpdatedTemplates|default()}}"
      - "Job Templates Removed: {{RemovedTemplates|default([])|count}}"
      - "========================"
      - "{{RemovedTemplates|default()}}"
      - "{{PostMsg|default()}}"
