---
- {name: Common Tasks, include_tasks: am_common.yml}
- {name: Image Management, include_tasks: image_management.yml, when: DoImgMgmt}
- {name: ZTP Management, include_tasks: ztp_management.yml, when: DoZtpMgmt}
- {name: Template Management, include_tasks: template_management.yml}

- name: Job Status
  debug:
    msg:
      - "Management Function: {{MgmtFunc|default('unspecified')}}"
      - "========================"
      - ""
      - "Job Templates Created: {{CreatedTemplates|default([])|count}}"
      - "========================"
      - "{{CreatedTemplates|default()}}"
      - "Job Templates Updated: {{UpdatedTemplates|default([])|count}}"
      - "========================"
      - "{{UpdatedTemplates|default()}}"
      - "Job Templates Removed: {{RemovedTemplates|default([])|count}}"
      - "========================"
      - "{{RemovedTemplates|default()}}"
      - "{{PostMsg|default()}}"
