---
- {name: Get Project Directory, uri: {url: '{{AwxApi}}/config/'}, register: AwxCfg}

- name: Get Project Info
  uri: {url: '{{AwxApi}}/projects/{{rThisTemplate.json.project}}/'}
  register: rPjInfo

- name: Set Job Variables
  set_fact:
    CreateJtPbs: []
    UpdateJtPbs: []
    UpdateJtTemplates: []
    UpdateJtVer: []
    VerRe: '^.*(playbook|template)_version: ([0-9].[0-9]).*$'
    PjId: "{{rThisTemplate.json.project}}"
    PjPath: "{{AwxCfg.json.project_base_dir}}/{{rPjInfo.json.local_path}}"

- name: Get Job Template Count
  uri: {url: '{{AwxApi}}/job_templates/'}
  register: JobTemplateCount

- name: Get List of All Templates
  uri: {url: '{{AwxApi}}/job_templates/?page_size={{JobTemplateCount.json.count}}'}
  register: AllTemplates

- name: Get List of Existing Job Templates for This Project
  set_fact: {ExistingTemplates: "{{tJts|selectattr('project', 'equalto', PjId|int)|list}}"}
  vars: {tJts: '{{AllTemplates.json.results}}'}

- name: Create/Update ICX Config Templates
  block:
  - name: Create/Update ICX Config Templates
    include_tasks: tm_sync_template_spec.yml

- name: Debug
  debug:
    msg:
      - "Job Templates Created"
      - "========================"
      - "{{CreatedTemplates|default(['none'])}}"
      - ""
      - "Job Templates Updated"
      - "========================"
      - "{{UpdatedTemplates|default(['none'])}}"
      - ""

- {name: End Play, meta: end_play}
