---
- {name: Get Project Directory, uri: {url: '{{AwxApi}}/config/'}, register: AwxCfg}

- name: Get Project Info
  uri: {url: '{{AwxApi}}/projects/{{rThisTemplate.json.project}}/'}
  register: rPjInfo

- name: Set Job Variables
  set_fact:
    VerRe: '^.*(playbook|template)_version: ([0-9].[0-9]).*$'
    PjId: "{{rThisTemplate.json.project}}"
    PjPath: "{{AwxCfg.json.project_base_dir}}/{{rPjInfo.json.local_path}}"

- name: Get Job Template Count
  uri: {url: '{{AwxApi}}/job_templates/'}
  register: rJtNum

- name: Get List of All Templates
  uri: {url: '{{AwxApi}}/job_templates/?page_size={{rJtNum.json.count}}'}
  register: rJts

- name: Create/Update ICX Config Templates
  block:
  - name: Set Template List
    set_fact: {UpdateTemplateList: '{{icx_config_templates}}'}

  - name: Create/Update ICX Config Templates
    include_tasks: tm_sync_template_spec.yml
    loop: '{{UpdateTemplateList}}'
    loop_control: {loop_var: bJtSpec}
    vars:
      bJt: "{{rJts.json.results|selectattr('name', '==', bJtSpec.name)|list}}"
  when: "'create' in MgmtFunc|lower"
