---
- name: Get Job Template Count
  uri: {url: '{{AwxApi}}/job_templates/'}
  register: rJtNum

- name: Load Management Template Specs
  include_vars: tm_spec_mgmt_templates.yml

- name: Get Job Templates
  uri: {url: '{{AwxApi}}/job_templates/?page_size={{rJtNum.json.count}}'}
  register: rJts

- name: Create/Update Management Templates
  block:
  - name: Create/Update Management Templates
    include_tasks: tm_sync_template_spec.yml
    loop: '{{mgmt_templates}}'
    loop_control: {loop_var: bJtSpec}
    vars:
      bJt: "{{rJts.json.results|selectattr('name', '==', bJtSpec.name)|list}}"
    when: bJtSpec.name is defined
  vars:
    bCreds: '{{rTemplateCreds|default("null", true)}}'
    bHaveCreds: '{{bCreds.results is defined}}'
    bAskCreds: '{{bJtSpec.ask_credential_on_launch|default(true)}}'

- name: Load ICX Config Template Specs
  include_vars: tm_spec_icx_config_templates.yml

- name: Create/Update ICX Config Templates
  block:
  - name: Set Template List
    set_fact: {UpdateTemplateList: '{{icx_config_templates}}'}

  - name: Create/Update ICX Config Templates
    include_tasks: tm_sync_template_spec.yml
    loop: '{{UpdateTemplateList}}'
    loop_control: {loop_var: bJtSpec}
    vars:
      bJt: "{{rJts.json.results|selectattr('name', '==', bJtSpec.name)|list}}"
  when: "'create' in MgmtFunc|lower"

- name: Remove ICX Config Templates
  block:
  - name: Set Template List
    set_fact: {RemoveTemplateList: '{{icx_config_template}}'}

  - name: Remove ICX Config Templates
    include_tasks: tm_remove_template.yml
    loop: '{{RemoveTemplateList}}'
    loop_control: {loop_var: bJtSpec}
    vars:
      bJt: "{{(rJts.json.results|selectattr('name', '==', bJtSpec.name)|list)}}"
    when: bJt[0].project|default(0) == rThisTemplate.json.project
  when: "'remove' in MgmtFunc|lower"
