---
- {name: Debug, debug: {msg: "Removing template {{bJtSpec.name}}"}}

- name: Remove Templates
  uri:
    url: '{{AwxApi}}/job_templates/{{bJt[0].id}}/'
    method: DELETE
    return_content: no
    status_code: 204
  no_log: '{{not log_secure_tasks}}'

- name: Add Template to "Removed" List
  set_fact:
    RemovedTemplates: '{{RemovedTemplates|default([]) + [bJtSpec.name]}}'
