---
- name: Get Template List
  uri: {url: '{{AwxApi}}/job_templates/?name={{item}}'}
  loop: '{{icx_config_templates}}'
  register: JobTemplates

- name: Remove Templates
  uri:
    url: '{{AwxApi}}/job_templates/{{JobTemplates.results[idx].json.results[0].id}}/'
    method: DELETE
    return_content: no
    status_code: 204
  loop: '{{icx_config_templates}}'
  loop_control: {index_var: idx}
  when:
    - JobTemplates.results[idx].json.results[0] is defined
    - JobTemplates.results[idx].json.results[0].project == rThisTemplate.json.project
