---
- name: Create Template
  block:
  - {name: Create Template, include_tasks: tm_sts_create_template.yml}
  when: bJt[0].id is not defined

- name: Update Template
  block:
  - name: Update Template
    include_tasks: tm_sts_update_template.yml
    vars: {bJtId: '{{rNewJt.json.id|default(bJt[0].id)}}'}
  vars:
    bEV: '{{bJt[0].extra_vars|default("playbook_rev: 0.0.0", true)}}'
    bPbSpecRev: '{{bJtSpec.playbook_rev|default("1.0.0")}}'
    bPbRev: '{{bEV|regex_search(regx_pb_ver)|regex_replace(regx_pb_ver, "\1")}}'
  when: not bDoRevCheck|default(true) or
        (bDoRevCheck|default(true) and bPbRev is version(bPbSpecRev, '<'))
