---
- name: Debug
  debug: msg="Creating template '{{bJtSpec.name}}'"

- name: Create Template
  uri:
    url: '{{AwxApi}}/job_templates/'
    method: POST
    headers: {Content-Type: "application/json"}
    body: "{{tTemplateStruct}}"
    body_format: json
    status_code: 201
  register: rNewJt
  vars:
    tTemplateStruct:
      name: '{{bJtSpec.name}}'
      project: '{{PjId}}'
      playbook: '{{bJtSpec.playbook}}'
      ask_credential_on_launch: true
      ask_inventory_on_launch: '{{prompt_ask_inventory_on_launch|default(true)}}'
      ask_limit_on_launch: true

- name: Add Template to "Created" List
  set_fact:
    CreatedTemplates: '{{CreatedTemplates|default([]) + [bJtSpec.name]}}'
