---
- name: If Updating Existing Template
  block:
  - {name: Debug, debug: {msg: "Updating template '{{bJtSpec.name}}'"}}

  - name: Add Template to "Updated" List
    set_fact: {UpdatedTemplates: '{{UpdatedTemplates|default([]) + [tEntry]}}'}
    vars: {tEntry: "{{bJtSpec.name}} {{bPbRev}} -> {{bPbSpecRev}}"}
  when: rNewJt.json.id|default("null", true) == "null"

- name: Add Survey Prompts
  uri:
    url: '{{AwxApi}}/job_templates/{{bJtId}}/survey_spec/'
    method: POST
    headers: {Content-Type: "application/json"}
    body: {name: '', description: '', spec: '{{bJtSpec.survey_spec}}'}
    body_format: json
  register: rPromptStatus
  when: bJtSpec.survey_spec|default("null", true) != "null"

- name: Update Template Options
  uri:
    url: '{{AwxApi}}/job_templates/{{bJtId}}/'
    method: PATCH
    headers: {Content-Type: "application/json"}
    body:
      description: '{{bJtSpec.description|default("", true)}}'
      ask_credential_on_launch: '{{not bHaveCreds or bAskCreds}}'
      use_fact_cache: '{{bJtSpec.use_fact_cache|default(false)}}'
      survey_enabled: '{{rPromptStatus.status|default(0, true) == 200}}'
      extra_vars: >-
        playbook_rev: {{bPbSpecRev}}

        {{bJtSpec.comments|default()}}
    body_format: json

- {name: Reset Vars, set_fact: {rNewJt: , rPromptStatus: }}
