---
- name: Check for Existence of ZTP Host Default Credentials
  uri: {url: '{{AwxApi}}/credentials/?name=ZTP_Default_Login'}
  register: ZtpCredStatus

- name: Create Initial Login Credentials
  block:
    - name: Get Info for This Job
      uri: {url: '{{AwxApi}}/jobs/{{awx_job_id}}/'}
      register: ThisJob

    - name: Get ID for 'Machine' Credential Type
      uri: {url: '{{AwxApi}}/credential_types/?name=Machine'}
      register: MachineCredType

    - name: Create Initial Login Credentials for ZTP Hosts
      uri:
        url: '{{AwxApi}}/credentials/'
        method: POST
        headers: {Content-Type: "application/json"}
        body:
          name: 'ZTP_Default_Login'
          credential_type: '{{MachineCredType.json.results[0].id}}'
          organization: '{{ThisJob.json.summary_fields.inventory.organization_id}}'
          inputs:
            password: '{{ZtpDefPassword}}'
            username: super
        body_format: json
        status_code: 201
  when: ZtpCredStatus.json.count == 0
