---
- name: Get ID for 'Machine' Credential Type
  uri: {url: '{{AwxApi}}/credential_types/?name=Machine'}
  no_log: '{{not log_secure_tasks}}'
  register: rMachineCredType

- name: Create Initial Login Credentials for ZTP Hosts
  uri:
    url: '{{AwxApi}}/credentials/'
    method: POST
    headers: {Content-Type: "application/json"}
    body:
      name: 'ZTP_Default_Login'
      credential_type: '{{rMachineCredType.json.results[0].id}}'
      organization: '{{bOrgId}}'
      inputs:
        password: '{{ZtpDefPass}}'
        username: super
    body_format: json
    status_code: 201
  no_log: '{{not log_secure_tasks}}'
