---
- name: Setup General ZTP Config
  set_fact: {ZtpCfg: '{{bZtpInvCfg.icx_ztp_cfg|default({})|combine(tGenCfg)}}'}
  vars:
    tGenCfgOld: '{{bZtpInvCfg.icx_ztp_cfg.general|default({})}}'
    tGenCfg:
      general:
        default_pass: '{{tGenCfgOld.default_pass|default(ZtpDefPass, true)}}'
        workflow: '{{tGenCfgOld.workflow|default()}}'
        awx_api_cb: '{{AwxApi}}'

- name: Create ZTP Inventory
  uri:
    url: '{{AwxApi}}/inventories/'
    method: POST
    headers: {Content-Type: "application/json"}
    body: {name: '{{ZtpInv}}', organization: '{{bOrgId}}'}
    body_format: json
    status_code: 201
  register: rNewInv
  when: bZtpInvInfo[0] is not defined

- name: Append IP Pool Config
  set_fact: {ZtpCfg: '{{ZtpCfg|combine(IpPoolCfg)}}'}
  when: IpPoolCfg is defined

- name: Append Hostname Pool Config
  set_fact: {ZtpCfg: '{{ZtpCfg|combine(HnPoolCfg)}}'}
  when: HnPoolCfg is defined

- name: Update Inventory Config
  uri:
    url: '{{AwxApi}}/inventories/{{tInvId}}/'
    method: PATCH
    headers: {Content-Type: 'application/json'}
    body:
      variables: >-
        {{tZtpCfg|to_nice_yaml(indent=2)}}
    body_format: json
  vars:
    tInvId: '{{rNewInv.json.id|default(bZtpInvInfo[0].id)}}'
    tVars: {icx_ztp_cfg: '{{ZtpCfg}}'}
    tZtpCfg: '{{bZtpInvCfg|combine(tVars)}}'
