---
- name: Check Files on AWX Host System
  block:
  - name: Check DHCP
    stat: {path: /etc/apparmor.d/usr.sbin.dhcpd}
    register: rDhcpFile
  connection: ssh
  vars:
    ansible_python_interpreter: '{{icx_awx_mgmt.ssh_interpreter}}'
    ansible_user: '{{awxssh_user|default(prompt_awxcli_user)}}'
    ansible_ssh_pass: '{{awxssh_pass|default(prompt_awxcli_pass)}}'

- name: Get Info on Installed Reqs From Server
  block:
  - name: Check For Existence of ZTP Default Credentials
    uri: {url: '{{AwxApi}}/credentials/?name=ZTP_Default_Login'}
    register: rZtpCreds

  - name: Check AWX Applications
    uri: {url: '{{AwxApi}}/applications/?name=isc-dhcp-server'}
    register: rZtpApp

  - name: Check For Existing Webhook Token
    uri: {url: '{{AwxApi}}/users/{{awx_user_id}}/tokens/?application={{tAppId}}'}
    register: rWebToken
    vars: {tAppId: '{{rZtpApp.json.results[0].id|default()}}'}
    when: tAppId|default("null", true) != "null"

- name: ZTP Setup
  block:
  - {name: Setup DHCP, include_tasks: zm_dhcp.yml, when: bDoDhcp}
  - {name: Create Creds, include_tasks: zm_default_creds.yml, when: bDoCred}
  - {name: Create Token, include_tasks: zm_auth_token.yml}
  vars:
    bOrgId: '{{rThisTemplate.json.organization}}'
    bDoDhcp: '{{not rDhcpFile.stat.exists}}'
    bDoCred: '{{rZtpCreds.json.count == 0}}'
