---
- name: Check Files on AWX Host System
  block:
  - name: Check DHCP
    stat: {path: /etc/apparmor.d/usr.sbin.dhcpd}
    register: rDhcpFile

  - name: Check Webhook
    stat: {path: /etc/dhcp/awx_dhcp_webhook}
    register: rWebhookFile
  connection: ssh
  vars:
    ansible_python_interpreter: '{{icx_awx_mgmt.ssh_interpreter}}'
    ansible_user: '{{awxssh_user|default(prompt_awxcli_user)}}'
    ansible_ssh_pass: '{{awxssh_pass|default(prompt_awxcli_pass)}}'

- name: Get Info on Installed Reqs From Server
  block:
  - name: Check For Existence of ZTP Default Credentials
    uri: {url: '{{AwxApi}}/credentials/?name=ZTP_Default_Login'}
    register: rZtpCreds

  - name: Check AWX Applications
    uri: {url: '{{AwxApi}}/applications/?name=isc-dhcp-server'}
    register: rZtpApp

  - name: Check For Existing Webhook Token
    uri: {url: '{{AwxApi}}/users/{{awx_user_id}}/tokens/?application={{tApp}}'}
    register: rWebToken
    vars: {tApp: '{{rZtpApp.json.results[0].id|default()}}'}
    when: tApp|default("null", true) != "null"

  - name: Get Inventory Count
    uri: {url: '{{AwxApi}}/inventories/'}
    register: rInvNum

  - name: Get Inventories
    uri: {url: '{{AwxApi}}/inventories/?page_size={{rInvNum.json.count}}'}
    register: rInvs
  no_log: '{{not log_secure_tasks}}'

- name: ZTP Setup
  block:
  - {name: Setup DHCP, include_tasks: zm_dhcp.yml, when: bDoDhcp}
  - {name: Create Creds, include_tasks: zm_default_creds.yml, when: bDoCred}
  - {name: Create Token, include_tasks: zm_auth_token.yml, when: bDoAuth}
  - {name: Configure Interface, include_tasks: zm_interface.yml, when: bDoInt}
  - {name: Create Inventory, include_tasks: zm_inventory.yml, when: IsZtpMgmt}
  vars:
    bOrgId: '{{rThisTemplate.json.organization}}'
    bAppId: '{{rZtpApp.json.results[0].id|default(0)}}'
    bTokId: '{{rWebToken.json.results[0].id|default(0)}}'
    bZtpInvInfo: '{{rInvs.json.results|selectattr("name", "==", ZtpInv)|list}}'
    bZtpInvCfg: '{{bZtpInvInfo[0].variables|from_yaml|default({}, true)}}'
    bNeedWebhook: '{{not rWebhookFile.stat.exists}}'
    bDoDhcp: '{{not rDhcpFile.stat.exists or DhcpCfgNew is defined}}'
    bDoCred: '{{rZtpCreds.json.count == 0}}'
    bDoAuth: '{{bAppId == "0" or bTokId == "0" or bNeedWebhook or IsZtpRT}}'
    bDoInt: '{{NetIntCfg is defined}}'
